// Shared medical guideline corpus (India / Bengaluru).
// Used by: the frontend (offline demo + fallback display) AND the backend
// ingestion script (chunk -> embed -> upsert into Qdrant).
//
// Each entry is treated as one retrievable chunk. `excerpt` is the text that
// gets embedded; the other fields are stored as Qdrant payload and shown in the
// Knowledge Base tab. `similarity` is only a placeholder for the offline/demo
// path — real retrieval replaces it with the live cosine score from Qdrant.
export const knowledgeBase = [
  { id: 'kb1', title: 'Cardiac Emergency Triage Protocol', source: 'AIIMS National Emergency Life Support (NELS) 2023 · ref. Sri Jayadeva Institute of Cardiovascular Sciences, Bengaluru', keywords: ['chest', 'heart', 'cardiac', 'arm pain', 'jaw', 'palpitation'], similarity: 0.94, chunk: 'Chunk 4 of 11 | 487 tokens', excerpt: 'Chest pain radiating to the arm, jaw, or shoulder with sweating or nausea should be treated as STEMI until proven otherwise. Activate 108 ambulance immediately and transfer to a PCI-capable centre (e.g. Sri Jayadeva Institute, Bengaluru). Do not delay for further assessment.' },
  { id: 'kb2', title: 'Stroke Recognition — FAST & Beyond', source: 'Indian Stroke Association Guidelines 2023 · ref. NIMHANS Stroke Unit, Bengaluru', keywords: ['face', 'arm weak', 'speech', 'slurred', 'headache', 'sudden'], similarity: 0.91, chunk: 'Chunk 2 of 9 | 512 tokens', excerpt: 'Use FAST: Facial drooping, Arm weakness, Speech difficulty, Time to call 108. Sudden "thunderclap" headache without trauma warrants urgent assessment for subarachnoid haemorrhage. Aim for a stroke-ready hospital within the thrombolysis window.' },
  { id: 'kb3', title: 'Headache Red Flags & Neurological Triage', source: 'AIIMS Neurology Protocols 2022 · ref. NIMHANS, Bengaluru', keywords: ['headache', 'head pain', 'migraine', 'worst', 'sudden'], similarity: 0.88, chunk: 'Chunk 1 of 7 | 431 tokens', excerpt: 'Red-flag headaches needing emergency referral: thunderclap onset, worst-ever headache, fever with neck stiffness, or focal neurology. Gradual-onset headaches with typical migraine features and no red flags may be managed in primary care (OPD).' },
  { id: 'kb4', title: 'Acute Respiratory Distress Triage', source: 'ICMR Acute Respiratory Care Guidance 2023', keywords: ['breathing', 'breath', 'breathe', 'chest tight', 'wheeze', 'oxygen'], similarity: 0.96, chunk: 'Chunk 3 of 8 | 502 tokens', excerpt: 'Patients unable to complete sentences, with SpO2 below 92%, or with bluish lips/cyanosis need an immediate 108 ambulance and casualty transfer. Assess for anaphylaxis, pulmonary embolism, and acute severe asthma.' },
  { id: 'kb5', title: 'Acute Abdominal Pain Assessment', source: 'ICMR / RGUHS Surgical Triage Pathway 2022', keywords: ['stomach', 'abdominal', 'belly', 'abdomen', 'nausea', 'vomiting'], similarity: 0.82, chunk: 'Chunk 6 of 14 | 498 tokens', excerpt: 'Peritonitis signs (board-like rigidity, rebound tenderness) and pulsatile abdominal mass need emergency referral. Fever with right iliac fossa tenderness warrants urgent surgical review. Mild non-specific pain with normal vitals may be observed.' },
  { id: 'kb6', title: 'Dengue & Paediatric Febrile Illness', source: 'MoHFW National Dengue Guidelines (NVBDCP) 2023 · ref. Indira Gandhi Institute of Child Health, Bengaluru', keywords: ['fever', 'dengue', 'rash', 'child', 'temperature', 'baby', 'infant', 'bleeding'], similarity: 0.9, chunk: 'Chunk 2 of 10 | 476 tokens', excerpt: 'Dengue warning signs — severe abdominal pain, persistent vomiting, bleeding gums, lethargy, or a fall in platelets — require same-day hospital assessment. Infants under 3 months with fever above 38°C, or any non-blanching rash with fever, are medical emergencies. Bengaluru sees seasonal dengue/chikungunya peaks post-monsoon.' },
  { id: 'kb7', title: 'Mental Health Crisis Assessment', source: 'NMHP / Tele-MANAS (14416) · ref. NIMHANS, Bengaluru', keywords: ['mental', 'anxiety', 'panic', 'self harm', 'self-harm', 'suicidal', 'depressed'], similarity: 0.81, chunk: 'Chunk 5 of 12 | 521 tokens', excerpt: 'Active suicidal ideation with plan and intent needs emergency psychiatric assessment (NIMHANS emergency, Bengaluru). First-presentation panic should be evaluated to exclude cardiac/respiratory causes. For distress without immediate risk, refer to Tele-MANAS on 14416.' },
  { id: 'kb8', title: 'Snakebite & Envenomation Protocol', source: 'ICMR / WHO Snakebite Management Guidelines 2023', keywords: ['snake', 'bite', 'snakebite', 'venom'], similarity: 0.83, chunk: 'Chunk 1 of 6 | 455 tokens', excerpt: 'Treat every snakebite as potentially venomous. Call 108, keep the patient calm and the limb immobilised at heart level, and reach a casualty with polyvalent anti-snake-venom. Do NOT apply tourniquets, cut, or attempt to suck the wound. Watch for ptosis, difficulty breathing, and bleeding.' },
  { id: 'kb9', title: 'Musculoskeletal Pain Stratification', source: 'RGUHS MSK Clinical Pathway 2022', keywords: ['back', 'joint', 'muscle', 'arm pain', 'leg', 'knee', 'shoulder'], similarity: 0.74, chunk: 'Chunk 8 of 15 | 463 tokens', excerpt: 'Red flags for back pain (cauda equina) include saddle anaesthesia, bilateral leg weakness, and loss of bladder/bowel control — refer immediately. Non-specific low back pain without red flags is suitable for self-management with physiotherapy if persistent.' },
]
